- name: Create a directory if it does not exist
  file:
    path: /tmp/docker-beginnerlinux1
    state: directory
    mode: '0755'

- name: Copy dockerfile
  copy:
      src: "{{ repo_path }}/roles/beginnerlinux1/docker/Dockerfile"
      dest: /tmp/docker-beginnerlinux1/Dockerfile
      mode: '0755'
      force: yes

- name: Build image
  docker_image:
    name: beginnerlinux1-image
    build:
      path: /tmp/docker-beginnerlinux1/
    source: build
    state: present
    force_source: yes
    repository: beginnerlinux1-image:latest
    force_tag: yes

- name: Run the container
  docker_container:
    name: beginnerlinux1-ssh
    image: beginnerlinux1-image
    state: started
    restart: yes
    expose: 22
    detach: yes
    published_ports: '6001:22'
