- name: Create a directory if it does not exist
  file:
    path: /tmp/docker-beginnerlinux8
    state: directory
    mode: '0755'

- name: Copy dockerfile
  copy:
      src: "{{ repo_path }}/roles/beginnerlinux8/docker/Dockerfile"
      dest: /tmp/docker-beginnerlinux8/Dockerfile
      mode: '0744'
      force: yes

- name: Copy program with the flag
  copy:
      src: "{{ repo_path }}/roles/beginnerlinux8/resources/giantsjournal.accdb"
      dest: /tmp/docker-beginnerlinux8/giantsjournal.accdb
      mode: '0744'
      force: yes

- name: Build image
  docker_image:
    name: beginnerlinux8-image
    build:
      path: /tmp/docker-beginnerlinux8/
    source: build
    state: present
    force_source: yes
    repository: beginnerlinux8-image:latest
    force_tag: yes

- name: Run the container
  docker_container:
    name: beginnerlinux8-ssh
    image: beginnerlinux8-image
    state: started
    restart: yes
    expose: 22
    detach: yes
    published_ports: '6008:22'
