---
- name: Configure challenge server
  hosts: all
  vars_files:
    - "vars/{{ env }}.yml"
  become: yes
  roles:
    - common
    - challenge1
    - challenge2
    - challenge3
    - challenge4
    - challenge5