---
- name: Configure challenge server
  hosts: all
  vars_files:
    - "vars/{{ env }}.yml"
  become: yes
  roles:
    - common
    - beginnerlinux1
    - beginnerlinux2
    - beginnerlinux3
    - beginnerlinux4
    - beginnerlinux5
    - beginnerlinux6
    - beginnerlinux7
    - beginnerlinux8
    - beginnerlinux9
    - beginnerlinux10
    - beginnerlinux11
    - beginnerlinux12
    - beginnerlinux13
    - beginnerweb1
    - binexploit1