- name: Create a directory if it does not exist
  file:
    path: /tmp/docker-beginnerweb2
    state: directory
    mode: '0755'

- name: Copy dockerfile
  copy:
      src: "{{ repo_path }}/roles/beginnerweb2/docker/Dockerfile"
      dest: /tmp/docker-beginnerweb2/Dockerfile
      mode: '0744'
      force: yes

- name: Copy entrypoint script
  copy:
      src: "{{ repo_path }}/roles/beginnerweb2/resources/entrypoint.sh"
      dest: /tmp/docker-beginnerweb2/entrypoint.sh
      mode: '0744'
      force: yes

- name: Copy ports.conf
  copy:
      src: "{{ repo_path }}/roles/beginnerweb2/resources/ports.conf"
      dest: /tmp/docker-beginnerweb2/ports.conf
      mode: '0700'
      force: yes

- name: Copy default site conf
  copy:
      src: "{{ repo_path }}/roles/beginnerweb2/resources/000-default.conf"
      dest: /tmp/docker-beginnerweb2/000-default.conf
      mode: '0700'
      force: yes

- name: Copy Site Content
  copy:
      src: "{{ repo_path }}/roles/beginnerweb2/resources/web_content/"
      dest: /tmp/docker-beginnerweb2/web_content/
      mode: '1700'
      force: yes

- name: Build image
  docker_image:
    name: beginnerweb2-image
    build:
      path: /tmp/docker-beginnerweb2/
    source: build
    state: present
    force_source: yes
    repository: beginnerweb2-image:latest
    force_tag: yes

- name: Run the container
  docker_container:
    name: beginnerweb2
    image: beginnerweb2-image
    state: started
    restart: yes
    expose: 8002
    detach: yes
    published_ports: '8002:8002'
