- name: Create a directory if it does not exist
  file:
    path: /tmp/docker-beginnerweb7
    state: directory
    mode: '0755'

- name: Copy dockerfile
  copy:
      src: "{{ repo_path }}/roles/beginnerweb7/docker/Dockerfile"
      dest: /tmp/docker-beginnerweb7/Dockerfile
      mode: '0744'
      force: yes

- name: Copy entrypoint script
  copy:
      src: "{{ repo_path }}/roles/beginnerweb7/resources/entrypoint.sh"
      dest: /tmp/docker-beginnerweb7/entrypoint.sh
      mode: '0744'
      force: yes

- name: Copy ports.conf
  copy:
      src: "{{ repo_path }}/roles/beginnerweb7/resources/ports.conf"
      dest: /tmp/docker-beginnerweb7/ports.conf
      mode: '0700'
      force: yes

- name: Copy default site conf
  copy:
      src: "{{ repo_path }}/roles/beginnerweb7/resources/000-default.conf"
      dest: /tmp/docker-beginnerweb7/000-default.conf
      mode: '0700'
      force: yes

- name: Copy Site Content
  copy:
      src: "{{ repo_path }}/roles/beginnerweb7/resources/web_content/"
      dest: /tmp/docker-beginnerweb7/web_content/
      mode: '1700'
      force: yes

- name: Build image
  docker_image:
    name: beginnerweb7-image
    build:
      path: /tmp/docker-beginnerweb7/
    source: build
    state: present
    force_source: yes
    repository: beginnerweb7-image:latest
    force_tag: yes

- name: Run the container
  docker_container:
    name: beginnerweb7
    image: beginnerweb7-image
    state: started
    restart: yes
    expose: 8007
    detach: yes
    published_ports: '8007:8007'
