- name: Create a directory if it does not exist
  file:
    path: /tmp/docker-beginnerlinux5
    state: directory
    mode: '0755'

- name: Copy dockerfile
  copy:
      src: "{{ repo_path }}/roles/beginnerlinux5/docker/Dockerfile"
      dest: /tmp/docker-beginnerlinux5/Dockerfile
      mode: '0744'
      force: yes

- name: Build image
  docker_image:
    name: beginnerlinux5-image
    build:
      path: /tmp/docker-beginnerlinux5/
    source: build
    state: present
    force_source: yes
    repository: beginnerlinux5-image:latest
    force_tag: yes

- name: Run the container
  docker_container:
    name: beginnerlinux5-ssh
    image: beginnerlinux5-image
    state: started
    restart: yes
    expose: 22
    detach: yes
    published_ports: '6005:22'
