- name: Create a directory if it does not exist
  file:
    path: /tmp/docker-beginnerlinux9
    state: directory
    mode: '0755'

- name: Copy dockerfile
  copy:
      src: "{{ repo_path }}/roles/beginnerlinux9/docker/Dockerfile"
      dest: /tmp/docker-beginnerlinux9/Dockerfile
      mode: '0744'
      force: yes

- name: Copy entrypoint script
  copy:
      src: "{{ repo_path }}/roles/beginnerlinux9/resources/entrypoint.sh"
      dest: /tmp/docker-beginnerlinux9/entrypoint.sh
      mode: '0744'
      force: yes

- name: Build image
  docker_image:
    name: beginnerlinux9-image
    build:
      path: /tmp/docker-beginnerlinux9/
    source: build
    state: present
    force_source: yes
    repository: beginnerlinux9-image:latest
    force_tag: yes

- name: Run the container
  docker_container:
    name: beginnerlinux9-ssh
    image: beginnerlinux9-image
    state: started
    restart: yes
    expose: 22
    detach: yes
    published_ports: '6009:22'
