- name: Pull alpine
  docker_image:
    name: alpine
    source: pull

- name: Run the container
  docker_container:
    name: challenge1-ssh
    image: alpine:latest
    state: started
    tty: yes
    expose: 22
    interactive: yes
    detach: no
    published_ports: '6001:22'
