- name: Pull alpine
  docker_image:
    name: alpine
    source: pull

- name: Run the container
  docker_container:
    name: challenge1-ssh
    image: alpine:latest
    command: /bin/sh
    state: started
    expose: 22
    detach: yes
    published_ports: '6001:22'
