- name: Create a directory if it does not exist
  file:
    path: /tmp/docker-challenge1
    state: directory
    mode: '0755'

- name: Copy dockerfile
  copy:
      src: "{{ repo_path }}/roles/challenge1/docker/Dockerfile"
      dest: /tmp/docker-challenge1/Dockerfile
      mode: '0755'
      force: yes


- name: Build image
  docker_image:
    name: challenge1-image
    build:
      path: /tmp/docker-challenge1/
    source: build

- name: Remove the container (if it exists)
  docker_container:
    name: challenge1-ssh
    state: absent

- name: Run the container
  docker_container:
    name: challenge1-ssh
    image: challenge1-image
    state: started
    expose: 22
    detach: yes
    published_ports: '6001:22'
