- name: Pull openssh server image
  docker_image:
    name: dockerbase/openssh-server
    source: pull

- name: Run the container
  docker_container:
    name: challenge1-ssh
    image: dockerbase/openssh-server:latest
    state: started
    expose: 22
    interactive: yes
    detach: yes
    published_ports: '6001:22'
