- name: Create a directory if it does not exist
  file:
    path: /tmp/docker-beginnerlinux2
    state: directory
    mode: '0755'

- name: Copy dockerfile
  copy:
      src: "{{ repo_path }}/roles/beginnerlinux2/docker/Dockerfile"
      dest: /tmp/docker-beginnerlinux2/Dockerfile
      mode: '0744'
      force: yes

- name: Build image
  docker_image:
    name: beginnerlinux2-image
    build:
      path: /tmp/docker-beginnerlinux2/
    source: build
    state: present
    force_source: yes
    repository: beginnerlinux2-image:latest
    force_tag: yes

- name: Run the container
  docker_container:
    name: beginnerlinux2-ssh
    image: beginnerlinux2-image
    state: started
    restart: yes
    expose: 22
    detach: yes
    published_ports: '6002:22'
