- name: Create a directory if it does not exist
  file:
    path: /tmp/docker-challenge4
    state: directory
    mode: '0755'

- name: Copy dockerfile
  copy:
      src: "{{ repo_path }}/roles/challenge4/docker/Dockerfile"
      dest: /tmp/docker-challenge4/Dockerfile
      mode: '0744'
      force: yes

- name: Copy program with the flag
  copy:
      src: "{{ repo_path }}/roles/challenge4/resources/super_secret_program"
      dest: /tmp/docker-challenge4/super_secret_program
      mode: '0744'
      force: yes

- name: Build image
  docker_image:
    name: challenge4-image
    build:
      path: /tmp/docker-challenge4/
    source: build
    state: present
    force_source: yes
    repository: challenge4-image:latest
    force_tag: yes

- name: Run the container
  docker_container:
    name: challenge4-ssh
    image: challenge4-image
    state: started
    restart: yes
    expose: 22
    detach: yes
    published_ports: '6004:22'
