- name: Create a directory if it does not exist
  file:
    path: /tmp/docker-binexploit1
    state: directory
    mode: '0755'

- name: Copy dockerfile
  copy:
      src: "{{ repo_path }}/roles/binexploit1/docker/Dockerfile"
      dest: /tmp/docker-binexploit1/Dockerfile
      mode: '0744'
      force: yes

- name: Copy binary program
  copy:
      src: "{{ repo_path }}/roles/binexploit1/resources/bin0"
      dest: /tmp/docker-binexploit1/bin0
      mode: '0755'
      force: yes

- name: Build image
  docker_image:
    name: binexploit1-image
    build:
      path: /tmp/docker-binexploit1/
    source: build
    state: present
    force_source: yes
    repository: binexploit1-image:latest
    force_tag: yes

- name: Run the container
  docker_container:
    name: binexploit1-ssh
    image: binexploit1-image
    state: started
    restart: yes
    expose: 22
    expose: 31337
    detach: yes
    published_ports: '6101:22'
    published_ports: '31337:31337'
